#!/usr/bin/env python
"""
Note: Executing this program on your respective os will remove all
the files from the present directory. And concatenate all the files
into one Big File.

Use it Carefully !

A python function that moves all the data/text from all the files
in a present directory in one file and removes all the other files
"""
import sys
import os
def fileConcatenator(f):
    for x in os.listdir('./'):
        print x
        output = open(x,'r')
        reading = output.read()
        writing = open(f,'w')
        writing.write(reading)
        os.remove(x)
    writing.close()

def main():
    myList= sys.argv
    bigfile = myList[1]
    v = fileConcatenator(bigfile)

if __name__ == "__main__":
    main()
"""
$ ./AllFilesConcatenator.py BigFile 
OneFile.py
cjar
BigFile
cookie.txt
crunch.txt

$ ls
BigFile

$ cat BigFile 
kfvifvnfjvn`o
P Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.facebook.com TRUE    /   FALSE   1480710648  fr0qLFNoF0jOfylRJKV..BXyzL5.2s.AAA.0.0.BXyzL5.AWWvx7MK


"""
